<table width="100%" border="0" cellspacing="0" cellpadding="5">
	<tr> 
		<td align="center" valign="top" class="subnav"> 
			<b>VIEW: </B> <a class="subnav" href="<?php echo $_SERVER['PHP_SELF'] ?>?function=tasks&mode=display&status=wip&owner_id=%25">[WIP]</a> &nbsp;&nbsp;&nbsp;
			<b>BROWSE: </B> <a class="subnav" href="<?php echo $_SERVER['PHP_SELF'] ?>?function=tasks&mode=browse">[Browse]</a> 
		</td>
	</tr>
</table>